components/Phenotype/Summary/index.tsx, pages/phenotypes/[id].tsx
Fetch and display data from endpoint and use same section for synonyms from gene page.
=> Update Phenotype summary

api-service/index.ts, components/Gene/Phenotypes/SignificantPhenotypes2/index.tsx, components/Gene/Publications/index.tsx, components/MoreItemsTooltip/index.tsx, components/Pagination/index.tsx, components/PublicationsList/index.tsx, components/PublicationsList/styles.module.scss, components/PublicationsList/types.ts, package.json, pages/_app.tsx, pages/publications/index.tsx, pages/publications/styles.module.scss, utils/chart/color.plugin.ts, yarn.lock
And updated publications section in Gene page
=> Added Publications page

components/Pagination/index.tsx
Fix bug related to latest changes to Publications page
=> Fix: Pagination component

components/ManhattanPlot/index.tsx, components/ManhattanPlot/styles.module.scss, components/PhenotypeGeneAssociations/index.tsx, components/Search/index.tsx, pages/phenotypes/[id].tsx
Added tooltip functionality to Manhattan plot based on Locuszoom.
Includes some other minor fixes
=> Manhattan tooltip

components/Gene/Phenotypes/AllData/index.tsx, styles/global.scss
Fixing cell in All data table of Phenotype section and updating table striped colours
=> Table updates

components/Header/index.tsx
Rewrite certain links of the main menu to be reachable from the page itself.
=> Rewrite links of main menu

components/Pagination/index.tsx, components/Pagination/styles.module.scss, components/PublicationsList/index.tsx, package.json, pages/cardiovascular/index.tsx, pages/embryo/index.tsx, pages/publications/index.tsx, pages/publications/styles.module.scss, public/mockServiceWorker.js, styles/global.scss, yarn.lock
Updated PublicationList and Pagination component
=> Updated Publication stats tab content

components/Data/Viability.tsx, components/Data/styles.module.scss, components/PieChart/index.tsx, pages/data/charts.tsx, pages/data/viability.tsx
- Adding viability data chart pages with mock data
- Change charts page to support viability, embryo viability
=> Viability chart page

components/Pagination/styles.module.scss, components/PublicationsList/index.tsx, pages/publications/index.tsx
Updated export table links, updated endpoints to fetch data for consortium papers and a specific grant agency and added download button to get file with all grant agencies.
=> Publications page updates

pages/histopath/index.tsx
Added sort by fixed tissue column and gene symbol, reset pagination on change, flipped top controls and added missing label
=> Updates to Histopath landing page

components/Gene/Phenotypes/StatisticalAnalysis/index.tsx, components/Gene/Phenotypes/index.tsx
Split loading indication based on data used
=> Update Phenotypes Gene section

api-service/index.ts, components/Gene/Expressions/index.tsx, components/Gene/Histopathology/index.tsx, components/Gene/HumanDiseases/index.tsx, components/Gene/Images/index.tsx, components/Gene/Order/index.tsx, components/Gene/Phenotypes/index.tsx, components/Gene/Publications/index.tsx, components/Gene/Summary/index.tsx, components/GeneResults/index.tsx, components/ManhattanPlot/styles.module.scss, components/PhenotypeResults/index.tsx, components/PublicationsList/index.tsx, pages/genes/[pid].tsx
Removed some console.log's, display averages from backend, updated titles in search results, made non content warnings consistent between sections of Gene page and fixed PublicationsList export button
=> Various improvements

components/Gene/Phenotypes/AllData/index.tsx, components/Gene/Phenotypes/SignificantPhenotypes2/index.tsx, components/Gene/Phenotypes/index.tsx, components/GeneResults/index.tsx, components/ManhattanPlot/index.tsx, components/ManhattanPlot/styles.module.scss, components/PhenotypeResults/index.tsx, components/PublicationsList/index.tsx, pages/phenotypes/[id].tsx, pages/publications/index.tsx, pages/publications/styles.module.scss
Updated Publications list and publications page, removed capitalisation from gene and phenotype results and updated Manhattan plot
=> Various improvements v3

components/Gene/Phenotypes/SignificantPhenotypes2/index.tsx, pages/phenotypes/[id].tsx
Update title of manhattan plot and update links in Significant Phenotypes table
=> Various improvements v4

components/Gene/Phenotypes/AllData/index.tsx, components/Gene/Phenotypes/SignificantPhenotypes2/index.tsx, components/PhenotypeGeneAssociations/index.tsx
=> Enable right click on links

components/Gene/Images/styles.module.scss, pages/genes/[pid]/images/[parameterStableId].tsx, pages/genes/[pid]/images/styles.module.scss
Added missing indicators (zygosity, age and allele symbol)
=> Feature - Image comparator indicators

components/Data/ABR.tsx, components/Data/BodyWeight.tsx, components/Data/EmbryoViability.tsx, components/Data/Plots/CategoricalBarPlot/index.tsx, components/Data/Plots/UnidimensionalBoxPlot/index.tsx, components/Data/Plots/UnidimensionalScatterPlot/index.tsx, components/Data/Plots/index.tsx, components/Data/Viability.tsx, pages/sexual-dimorphism/index.tsx, utils/chart/index.ts
Picked 2 colors (#1A85FF and #D41159) from this page: https://davidmathlogic.com/colorblind/ to address possible issues with colourblind users.
=> Update colors used in charts

components/Data/BodyWeight.tsx, components/Data/ChartSummary.tsx, components/Data/DataComparison/index.tsx, components/Gene/Summary/index.tsx, components/Pagination/index.tsx, components/skeletons/table.tsx, hooks/bodyweight.query.ts, pages/data/charts.tsx
=> Compound bodyweight chart

components/Data/DataComparison/index.tsx, pages/data/charts.tsx
=> Fix: Data comparison bug

components/Gene/Phenotypes/SignificantPhenotypes/index.tsx
=> fix: Gene phenotypes, check for error before filtering

components/Data/BodyWeight.tsx, components/Data/Categorical.tsx, components/Data/TimeSeries.tsx, components/Data/Unidimensional.tsx, components/Gene/Summary/index.tsx, components/PhenotypeGeneAssociations/index.tsx, components/SmartTable/Cells/SignificantPValue.tsx, pages/cardiovascular/index.tsx, pages/data/bodyweight.tsx, pages/data/charts.tsx, pages/data/viability.tsx, pages/embryo/index.tsx, pages/hearing/index.tsx, pages/histopath/index.tsx, pages/metabolism/index.tsx, pages/sexual-dimorphism/index.tsx, styles/bootstrap-overwrite.scss
- Update links and text in Gene summary
- Fixed issue with Phenotype genotype associations table
- Update breadcrumbs to remove links
- Update note regarding download all info in chart pages
=> Small updates

components/Gene/Histopathology/index.tsx, pages/data/histopath/[pid].tsx, pages/genes/[pid].tsx, shared/hooks/gene-summary.query.ts, shared/hooks/histopathology.query.ts, shared/hooks/index.ts, shared/models/histopathology.ts, shared/models/index.ts
Finished 1st version for Histopathology chart page, with basic filtering
=> Histopathology chart

components/AlleleSymbol/index.tsx, components/index.ts, pages/data/histopath/[pid].tsx, pages/genes/[pid]/images/[parameterStableId].tsx, shared/hooks/histopathology.query.ts, shared/models/histopathology.ts
Add new fields, added images section and modals
=> Update histopathology chart

pages/data/histopath/[pid].tsx, shared/hooks/histopathology.query.ts
- Remove modal showing full size image
- Remove query param after anatomy filter was removed
=> Update histopath chart

.env.test, __tests__/components/Gene/Expressions.test.tsx, __tests__/components/Gene/HumanDiseases.test.tsx, __tests__/components/Gene/Summary.test.tsx, components/Gene/Expressions/custom-cells.tsx, components/Gene/Histopathology/index.tsx, components/Gene/Order/index.tsx, components/Gene/Publications/index.tsx, components/Gene/Summary/index.tsx, components/MoreItemsTooltip/index.tsx, components/SmartTable/SmartTable.tsx, components/SortableTable/index.tsx, jest.setup.js
Updated some test and remove React key warnings
=> Fix some test

components/ManhattanPlot/DataTooltip.tsx, components/ManhattanPlot/index.tsx
- Check genes with significant flag as true, put a high value to appear in the chart
- Show legend for significant genes in Manhattan plot
=> Update Manhattan Plot

components/ManhattanPlot/DataTooltip.tsx, components/ManhattanPlot/index.tsx
- Making search case insensitive
- Improving tooltip position
- Added P-Value threshold line
=> Updates to Manhattan Plot

pages/release.tsx
Using memo to save chart values in rerenders
=> Release page - Order phenotype calls

components/Allele/AlleleMap.tsx/index.tsx, components/Gene/Summary/index.tsx, components/Pagination/index.tsx, styles/global.scss
Also this PR includes:
- Improved logic to show/hide pagination controls
- Displaying AlleleMap section only if has data
=> [Gene summary] - Remove order alleles button

components/Check.tsx, components/Gene/Summary/index.tsx, components/Gene/Summary/styles.module.scss, components/GeneComparator/index.tsx, components/Newsletter/index.tsx, styles/global.scss, styles/vars.scss
- Updated size and shape of phy. system numbers in Gene section
- Updated styles of Data collection icons, set in black to increase contrast
=> Update links colors

shared/hooks/gene-associations.query.ts, shared/hooks/significant-phenotypes.query.ts
- Also take into consideration life stage in significant phenotypes and gene phenotype associations table.
=> [Significant Phenotypes table] - Fix significant phenotypes query to display all sexes for each hit

components/FilterBox/FilterBox.tsx, components/Gene/Summary/index.tsx, pages/genes/[pid]/images/[parameterStableId].tsx, pages/genes/[pid]/images/styles.module.scss, shared/models/gene/images.ts, shared/models/gene/index.ts, styles/bootstrap-overwrite.scss, styles/components/_badges.scss, styles/global.scss
=> [Image comparator] - Updated layout, added info to selected imaged and filters

components/EmbryoDataAvailabilityGrid/index.tsx, components/FilterBox/FilterBox.tsx, components/Gene/Phenotypes/AllelePhenotypeDiagram/index.tsx, components/Layout/index.tsx, components/Pagination/index.tsx, components/PublicationsList/index.tsx, components/Search/index.tsx, components/SortableTable/index.tsx, next.config.js, pages/cardiovascular/index.tsx, pages/conservation/index.tsx, pages/data/bodyweight.tsx, pages/data/charts.tsx, pages/data/histopath/[pid].tsx, pages/data/viability.tsx, pages/embryo/index.tsx, pages/genes/[pid].tsx, pages/genes/[pid]/download-images/[parameterStableId].tsx, pages/genes/[pid]/images/[parameterStableId].tsx, pages/hearing/index.tsx, pages/histopath/index.tsx, pages/metabolism/index.tsx, pages/phenotypes/[id].tsx, pages/publications/index.tsx, pages/release.tsx, pages/search.tsx, pages/sexual-dimorphism/index.tsx
Still there are some contrast issues
=> Fix: Accessibility issues across the site

components/Data/ABR.tsx, components/Data/BodyWeight.tsx, components/Data/Categorical.tsx, components/Data/TimeSeries.tsx, components/Data/Unidimensional.tsx, components/DownloadData/index.tsx, components/Gene/Phenotypes/AllData/index.tsx, components/Gene/Phenotypes/AllelePhenotypeDiagram/index.tsx, components/Gene/Phenotypes/SignificantPhenotypes/index.tsx, components/Gene/Summary/index.tsx, components/Gene/Summary/styles.module.scss, components/Pagination/index.tsx, components/Pagination/styles.module.scss, components/SmartTable/Cells/PhenotypeIcons.tsx, components/SmartTable/Cells/SignificantPValue.tsx, pages/alleles/[pid]/[alleleSymbol].tsx, pages/alleles/[pid]/styles.module.scss, pages/data/bodyweight.tsx, pages/data/charts.tsx, pages/data/histopath/[pid].tsx, pages/data/viability.tsx, pages/genes/[pid]/images/[parameterStableId].tsx, pages/phenotypes/[id].tsx, styles/components/_buttons.scss, styles/global.scss, styles/vars.scss, utils/index.tsx
- Update button styles based on Carla's design
- Fix accessibility and contrast issues
- Fix layout issues with bottom controls of Pagination component
- Update back link on child pages (Chart, Histopath, Image comparator, Bodyweight, Viability)
- Update buttons across the site to use the new styles
- Move link to supporting data to Systems column in Phenotypes tables
- List procedures alphabetically in Phenotype page
- Minor responsive changes
=> Design, layout and accessibility updates

components/SmartTable/SmartTable.tsx, pages/data/histopath/[pid].tsx
Avoid showing the message "no data available" whilst fetching data
=> [Histopath page] - Add loading state to table

components/ManhattanPlot/index.tsx
Get point with lowest p Value and discard those with null
=> [Manhattan plot] - Deduplicate points with same gene symbol

components/Data/PPI.tsx, shared/hooks/significant-phenotypes.query.ts
Filter global parameter in PPI chart page
=> [Significant Phenotypes table] - Only count datasets of % PPI parameters

components/Gene/Phenotypes/StatisticalAnalysis/index.tsx, components/Gene/Phenotypes/StatisticalAnalysis/styles.module.scss, components/Gene/Phenotypes/index.tsx, utils/index.tsx
=> [Graphical analysis chart] - General enhancements

components/Gene/HumanDiseases/index.tsx, components/Gene/Phenotypes/StatisticalAnalysis/index.tsx, components/Gene/Phenotypes/StatisticalAnalysis/styles.module.scss, components/ZoomButtons/ZoomButtons.tsx, components/index.ts, pages/genes/[pid]/images/[parameterStableId].tsx
- Add tooltip in human diseases section to display phenodigm score
- Updated zoom icons in Image comparator and Graphical analysis tab, add tooltips, created shared component
=> Graphical Analysis and Human diseases section updates

components/ManhattanPlot/index.tsx
=> [Manhattan Plot] - Set different colour to manual associations

components/Data/ABR.tsx, components/Data/DataComparison/index.tsx, components/Gene/Phenotypes/AllData/index.tsx, pages/data/charts.tsx, utils/index.tsx
- Update getSmallestPValue function to consider all values for each dataset
=> [Data comparison] - Show all significant icons for each row

components/Data/ABR.tsx, components/Data/IPGTT.tsx, components/Data/PPI.tsx, shared/hooks/related-parameters.query.ts
Add update general chart loading indicator to use new flag
=> [PPI chart] - Update loading indicator logic

components/FilterBox/FilterBox.tsx, components/Gene/Phenotypes/AllData/index.tsx
Also send the param while fetching all data for download
=> [All data table] - Search box functionality

components/Gene/Phenotypes/AllData/custom-cells.tsx, components/Gene/Phenotypes/AllData/index.tsx, components/Gene/Phenotypes/index.tsx
And update icon for n-numbers highlighted rows
=> [All data table] - Counts in tab name

components/Allele/AlleleMap.tsx/index.tsx, components/Gene/Phenotypes/AllData/custom-cells.tsx, components/Gene/Phenotypes/AllData/index.tsx, components/Gene/Phenotypes/GraphicalAnalysis/GraphicalAnalysisChart.tsx, components/SmartTable/Cells/Options.tsx, pages/alleles/[pid]/[alleleSymbol].tsx, pages/release.tsx
Also adding "Not analyzed" in signficant column of All data table
=> Small updates: Graphical analysis, n-numbers highlight, Ensembl link

components/Header/index.tsx, components/Layout/index.tsx, components/Search/styles.module.scss, next.config.js
=> Set base URL config to /data

.env.production, components/Search/index.tsx, pages/search.tsx
Also add compatibility with WP site using "term" query instead of "query"
=> Test: set API_ROOT env var to / to transform url to relative one

components/Gene/Expressions/index.tsx, components/Gene/Histopathology/index.tsx, components/Gene/HumanDiseases/index.tsx, components/Gene/Images/index.tsx, components/Gene/Order/index.tsx, components/Gene/Phenotypes/index.tsx, components/Gene/Publications/index.tsx, components/SectionHeader/SectionHeader.tsx
=> [Help indicators] - Added them to most of gene page sections

components/Gene/Phenotypes/AllData/custom-cells.tsx, components/GeneResults/index.tsx, components/PleiotropyChart/index.tsx, components/Search/index.tsx, pages/embryo/index.tsx, pages/genes/[pid]/images/[parameterStableId].tsx, pages/search.tsx, shared/models/gene/images.ts
- remove gene comparator from search results
- handle phenotype search requests from WP site
-  drop n-numbers footnote symbol on rows with N/A
- fix footnote highlighting functionality for n-numbers
- update histopathology links from all data table
- update pleiotropy chart dimensions
=> Minor fixes

components/EmbryoDataAvailabilityGrid/index.tsx, pages/_app.tsx, pages/embryo/index.tsx
Removed refetch on focus global query config and removed some unused imports
=> [Embryo landing page] - Update UMASS column to Mager Lab

components/ReleasePage/CallsTrendChart/index.tsx, components/ReleasePage/DataPointsTrendChart/index.tsx, components/ReleasePage/index.ts, pages/release.tsx, shared/models/index.ts, shared/models/release.ts
Added DR 21.1 to list of past releases with corresponding pdf report
=> [Release page] -  add Trends charts

components/BodySystemIcon/index.tsx, components/BodySystemIcon/styles.module.scss, components/Data/DataComparison/BodyWeightDataComparison.tsx, components/Data/DataComparison/ViabilityDataComparison.tsx, components/Data/DataComparison/index.tsx, components/Gene/Histopathology/index.tsx, components/Gene/HumanDiseases/index.tsx, components/Gene/Order/index.tsx, components/Gene/Publications/index.tsx, components/SortableTable/index.tsx, pages/batchQuery/index.tsx, shared/models/index.ts, shared/models/sortableTable.ts
- Added pagination
- Sorting and filtering by phy. system
- fix: re-rendering issue with SortableTable default sort prop
- add tab to choose the type of id's (if user has put something in the textarea and selected a file)
=> [Batch query] - UX updates

components/Data/GrossPathology.tsx, pages/supporting-data/index.tsx, shared/hooks/gene-summary.query.ts, shared/hooks/gross-pathology-chart.query.ts, shared/models/gross-pathology.ts
=> [Gross pathology chart] - Add anatomy term to table

components/Data/DataComparison/utils.ts
and avoid setting a null value
=> [Data comparison] - Remove null values when comparing reportedPValue and statistical method attributes pValue

components/Gene/Metadata/metadata.tsx, components/Gene/Summary/index.tsx, components/Header/index.tsx, pages/batchQuery/index.tsx
Added error boundary to Gene summary section to avoid crashing entire page
=> Updates before switch over

components/Gene/Phenotypes/index.tsx
to fetch data and populate order phenotyped column
=> [All phenotype data table] - Revert lazy loading

.env.production, components/Data/Categorical.tsx, components/Data/DataComparison/index.tsx, components/Data/DataComparison/utils.ts, components/Data/Unidimensional.tsx, components/Gene/Order/index.tsx, pages/alleles/[pid]/[alleleSymbol].tsx, pages/supporting-data/index.tsx, shared/hooks/significant-phenotypes.query.ts, utils/index.tsx
- add missing www to api root
- formatAlleleSymbol: check if value is falsy before formatting
- encode allele symbol on Gene order and Allele page
- add error handling to Allele page fetching
- update DataComparison table: highlight 0 pValues, check for nulls and undefined, add missing sex icons
- getSmallestPValue: update logic to filter null and undefined values
- add safe operator access to phenotypeSex prop to display sex icons
- unidimensional and categorical chart, set default N/A value if is null or undefined
- processGenePhenotypeHitsResponse: set null default value for topLevelPhenotypeName
- DataComparison: if sex is null and attributes.genotypeEffectPValue has a value, set it in pValue_not_considered prop
=> Bugs fixed after release

components/Layout/index.tsx, logger.ts
And set ISO format of timestamps in logs
=> Javascript disabled banner

components/Data/GrossPathology.tsx, components/Gene/Expressions/index.tsx, components/Gene/Phenotypes/AllData/index.tsx, components/Gene/Phenotypes/Footnotes/index.tsx, components/Gene/Phenotypes/SignificantPhenotypes/index.tsx, components/Phenotype/GeneAssociations/index.tsx, components/SmartTable/SmartTable.tsx, pages/embryo/index.tsx, pages/genes/[pid]/download-images/[parameterStableId].tsx, pages/hearing/index.tsx, pages/metabolism/index.tsx, pages/release.tsx, pages/supporting-data/gross-pathology/[pid].tsx, pages/supporting-data/histopath/[pid].tsx
Also, apply fix to all usages of SmartTable component
=> [All phenotype data]: Fix - sorting and footnote wording 

components/GeneResults/index.tsx, utils/results-page.tsx
Improve highlight matching to be case-insensitive
=> [Gene search] - Add human symbol and synonyms

components/Gene/Order/index.tsx, pages/alleles/[pid]/[...alleleSymbol].tsx
Add catch-all segment to allele page to handle allele names with slashes
=> [allele page] fix: allele names with slashes

api-service/index.ts, impc-nextjs-frontend-deployment.yaml
And read the env variable on every request to get the updated var
=> [dev deployment] Set NEXT_PUBLIC_API_ROOT in deployment yaml

components/Allele/IVP/index.tsx, components/Gene/HumanDiseases/index.tsx, components/Gene/Summary/index.tsx, components/Phenotype/Summary/index.tsx, components/Phenotype/Summary/styles.module.scss, components/SectionHeader/SectionHeader.tsx, components/SortableTable/index.tsx, components/SortableTable/styles.module.scss, components/index.ts, shared/models/sortableTable.ts
- updated Phenotype summary, reducing synonyms font size
- add external link icon to MGI site links in Phenotype and Gene summary
- reordered columns in Human diseases section
- moved help link to phenodigm score table header
- fix: link to design oligo page in intermediate vector section of allele page
=> Minor fixes and updates

api-service/server/supporting-page.ts, components/Gene/Phenotypes/AllData/custom-cells.tsx, shared/hooks/datasets.query.ts, shared/models/TableCell.ts, shared/models/chart.ts
Fixes issue _Alad_ - Platelet count chart page issue
=> [Chart page]: Include metadataGroup in request URL to dataset service

.env.development, api-service/index.ts, api-service/server/allele-page.ts, api-service/server/gene-page.ts, api-service/server/image-comparator-page.ts, api-service/server/phenotype-page.ts, api-service/server/search-page.ts, api-service/server/supporting-page.ts, impc-nextjs-frontend-deployment.yaml
Specify "local" in the .env.development and "development" in the deployment yaml file.
Fetch using external domain if WEBSITE_ENV == "local"
And fix typo in supporting data endpoint find_by_parameter
=> [General] - Change from NODE_ENV to WEBSITE_ENV

api-service/server/gene-page.ts, app/genes/[pid]/gene-page.tsx, app/genes/[pid]/page.tsx, components/Gene/HumanDiseases/index.tsx, components/Gene/index.ts, shared/models/gene/disease.ts
Get only required data divided by boolean parameter associationCurated
=> [Human diseases] - Split data fetching by associationCurated

app/genes/[pid]/download-images/[parameterStableId]/page.tsx, app/genes/[pid]/images/[parameterStableId]/page.tsx, app/sexual-dimorphism/sexual-dimorphism-page.tsx, app/supporting-data/bodyweight/page.tsx, app/supporting-data/gross-pathology/[pid]/page.tsx, app/supporting-data/histopath/[pid]/page.tsx, app/supporting-data/page.tsx, app/supporting-data/viability/page.tsx, components/Data/PPI.tsx, components/Data/Plots/UnidimensionalBoxPlot/index.tsx, shared/chart-js-plugins/boxplot-tooltip-label-multiline/index.ts
- Updated title to chart, image viewer and downloader pages
- Updated label of tooltips for charts with boxplots/violin
=> Page metadata and boxplot updates

app/genes/[pid]/page.tsx, components/Gene/HumanDiseases/index.tsx
To handle cases like Trp53 that had a lot of data
=> [Gene page] - Remove Human disease fetching from backend

app/genes/[pid]/download-images/[parameterStableId]/image-downloader-page.tsx, app/genes/[pid]/gene-page.tsx, components/Gene/Order/index.tsx, components/Gene/Summary/index.tsx, shared/contexts/index.ts, styles/components/_badges.scss, styles/components/_buttons.scss, styles/components/_pagination.scss
Darken green colour and apply white color to text
=> [Button styles] - Update primary button styles

app/genes/[pid]/gene-page.tsx, components/Gene/Summary/index.tsx
Removed "available" word, increased the font size and weight
=> [Gene summary] - Update text and styles of CTA button

components/Phenotype/GeneAssociations/index.tsx, components/Phenotype/ManhattanPlot/index.tsx
Display no data alert in both sections (table associations and manhattan plot)
=> [Phenotype page] - Handle endpoint errors for Manhattan plot

components/Header/index.tsx
And change default value to prod one
=> [Header] - Add mousephenotype.org case when loading prod menu json

components/Data/Categorical.tsx, components/Data/Unidimensional.tsx
For Unidimensional and Categorical charts in results of statistical analysis
=> [Chart pages] - Update logic to display combined p value

__tests__/components/Pages/Gene.test.tsx, __tests__/pages/__snapshots__/abr-chart-page.test.tsx.snap, __tests__/pages/__snapshots__/bodyweight-chart-page.test.tsx.snap, __tests__/pages/__snapshots__/categorical-chart-page.test.tsx.snap, __tests__/pages/__snapshots__/embryo-viability-chart-page.test.tsx.snap, __tests__/pages/__snapshots__/ppi-chart-page.test.tsx.snap, __tests__/pages/__snapshots__/timeseries-chart-page.test.tsx.snap, __tests__/pages/__snapshots__/unidimensional-chart-page.test.tsx.snap, __tests__/pages/__snapshots__/viability-chart-page.test.tsx.snap, __tests__/pages/unidimensional-chart-page.test.tsx, app/designs/[id]/designs-page.tsx, components/Data/ChartNav/ChartNav.tsx
Wait until page finishes loading
=> [Test suite] - Improve unidimensional chart page and Gene page tests

components/ReleasePage/release.tsx, shared/models/release.ts
=> [Release page] - Update by center charts data generation script

app/embryo/embryo-page.tsx, app/supporting-data/supporting-data-page.tsx, components/Gene/Phenotypes/SignificantPhenotypes/custom-cells.tsx, shared/hooks/datasets.query.ts, shared/models/chart.ts
And include updated links in embryo landing page
=> [Chart page] - Include extra query params to match number of supporting datasets

shared/hooks/datasets.query.ts
Check for alleleAccessionId and lifeStageName that contain a truthy value before using it on the url
=> [Chart page] - Check additional params before appending to URL

components/Data/DataComparison/index.tsx, components/Data/StatisticalMethodTable.tsx, components/Data/Unidimensional.tsx, components/Gene/Phenotypes/AllData/index.tsx, components/Gene/Phenotypes/Footnotes/index.tsx, components/Gene/Phenotypes/GraphicalAnalysis/GraphicalAnalysisChart.tsx, components/Gene/Phenotypes/GraphicalAnalysis/index.tsx, components/Gene/Phenotypes/SignificantPhenotypes/index.tsx, components/Phenotype/GeneAssociations/index.tsx, components/Phenotype/ManhattanPlot/DataTooltip.tsx, components/Phenotype/ManhattanPlot/index.tsx
And add statistical method name at top of the table
Ensure spelling of "P-Value" across the website
=> [Chart page] - Display correct values in Statistical Method table

app/supporting-data/page.tsx
Check number of datasets and if is zero, return 404
=> [Chart pages] - Improved 404 page

components/Gene/Phenotypes/AllData/custom-cells.tsx
=> [All data table] - Fix All data table link to Pain landing page

components/Data/Unidimensional.tsx
If statistical method is Reference Range
=> [Chart page] - Conditionally display windowing parameters section

components/Data/StatisticalAnalysisDownloadLink.tsx, components/Data/StatisticalMethodTable/StatisticalMethodTable.tsx, components/Data/StatisticalMethodTable/styles.module.scss
- Fix typo in Statistical Analysis download link (reported by @marinak-ebi)
- Added link in Statistical method table directing to help pages
=> Updates to chart pages

components/Data/TimeSeries.tsx, components/Gene/HumanDiseases/index.tsx, components/Gene/Phenotypes/AllData/custom-cells.tsx, components/SmartTable/Cells/SignificantPValue.tsx, utils/index.tsx
Includes:
- Displaying P-Values as "N/A" for NotProcessed data
- Display correctly Passive rotation chart page from ICS (Rotarod)
- Fix Phenogrid when no associatedDiseases exists
- Fix link to DECIPHER website from the Human diseases section
=> Bug fixes for live website

components/Data/ABR.tsx, shared/hooks/related-parameters.query.ts
Fix: experimental data file download
=> [ABR Chart page] - Fix: experimental data file download

components/Data/StatisticalMethodTable/StatisticalMethodTable.tsx, components/Data/Unidimensional.tsx
Display initial value, set as "Supplied as data" and needs further discussion
=> [Unidimensional chart page]: Handle null statistical method name

app/alleles/[pid]/[...alleleSymbol]/allele-page.tsx
=> [Allele page] - Hide Allele map section if Allele was produced by Velocigene strategy

__tests__/components/LandingPages/__snapshots__/embryo.test.tsx.snap, __tests__/components/LandingPages/embryo.test.tsx
=> [unit tests] fix: Embryo landing page 
